services:
  frontend:
    build: ./frontnoend
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=app
#      - PUBLIC_API_URL=http://app:8080/api

  app:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/shopping_platform?authSource=admin
      - WEB3_RPC_URL=http://hardhat:8545
    volumes:
      - ./backend/backend/data-seed:/data

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=shopping_platform'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - ./backend/backend/data-seed:/data
      - ./backend/backend/seed.sh:/docker-entrypoint-initdb.d/seed.sh

  hardhat:
    build:
      context: ./backend/smart-contract
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./backend/smart-contract:/app