server:
  port: 8080

spring:
  data:
    mongodb:
#      mongodb cloud (not needed yet(?))
#      uri: mongodb+srv://mongo:P%40ssword123@cluster0.bfooric.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      uri: mongodb://root:secret@localhost:27017/?retryWrites=true&w=majority&appName=Cluster0
      database: shopping_platform
      username: root
      password: secret

security:
  accessTokenExpirationInMs: 86400000 # 1 day
  refreshTokenExpirationInMs: 7776000000 # 90 days
  secret-key: FB3B63E6E94DFA04C3C10E2E2C2CCC001EF83C13F504F76A93CA874B701415E1
