server:
  port: 8080

spring:
  data:
    mongodb:
      # =============================================== Atlas ===============================================
      #      uri: mongodb+srv://mongo:P%40ssword123@cluster0.bfooric.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #      database: shopping_platform
      # =============================================== Old docker  ===============================================
      #      uri: mongodb://root:secret@localhost:27017/?retryWrites=true&w=majority&appName=Cluster0
      #      username: root
      #      password: secret
      # =============================================== New Docker ===============================================
      uri: ${SPRING_DATA_MONGODB_URI}
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

web3:
  rpc:
    #    url: "http://127.0.0.1:8545"
    url: "http://hardhat:8545"
  contract:
    address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    tikTokAddress: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
  wallet:
    private-key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # account 0

security:
  accessTokenExpirationInMs: 86400000 # 1 day
  refreshTokenExpirationInMs: 7776000000 # 90 days
  secret-key: FB3B63E6E94DFA04C3C10E2E2C2CCC001EF83C13F504F76A93CA874B701415E1
